config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :superpowers
  resources :superheroes
  resources :superpowers, only: [:index]
  resources :superheroes, only: [:index]


# root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/superhero.rb
class Superhero < ApplicationRecord
end

app/models/superpower.rb
class Superpower < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/superheroes_controller.rb
class SuperheroesController < ApplicationController
  before_action :set_superhero, only: [:show, :edit, :update, :destroy]

  # GET /superheroes
  # GET /superheroes.json
  def index
    @superheroes = Superhero.all
  end

  # GET /superheroes/1
  # GET /superheroes/1.json
  def show
  end

  # GET /superheroes/new
  def new
    @superhero = Superhero.new
  end

  # GET /superheroes/1/edit
  def edit
  end

  # POST /superheroes
  # POST /superheroes.json
  def create
    @superhero = Superhero.new(superhero_params)

    respond_to do |format|
      if @superhero.save
        format.html { redirect_to @superhero, notice: 'Superhero was successfully created.' }
        format.json { render :show, status: :created, location: @superhero }
      else
        format.html { render :new }
        format.json { render json: @superhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /superheroes/1
  # PATCH/PUT /superheroes/1.json
  def update
    respond_to do |format|
      if @superhero.update(superhero_params)
        format.html { redirect_to @superhero, notice: 'Superhero was successfully updated.' }
        format.json { render :show, status: :ok, location: @superhero }
      else
        format.html { render :edit }
        format.json { render json: @superhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /superheroes/1
  # DELETE /superheroes/1.json
  def destroy
    @superhero.destroy
    respond_to do |format|
      format.html { redirect_to superheroes_url, notice: 'Superhero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_superhero
      @superhero = Superhero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def superhero_params
      params.require(:superhero).permit(:name)
    end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
  before_action :set_superpower, only: [:show, :edit, :update, :destroy]

  # GET /superpowers
  # GET /superpowers.json
  def index
    @superpowers = Superpower.all
  end

  # GET /superpowers/1
  # GET /superpowers/1.json
  def show
  end

  # GET /superpowers/new
  def new
    @superpower = Superpower.new
  end

  # GET /superpowers/1/edit
  def edit
  end

  # POST /superpowers
  # POST /superpowers.json
  def create
    @superpower = Superpower.new(superpower_params)

    respond_to do |format|
      if @superpower.save
        format.html { redirect_to @superpower, notice: 'Superpower was successfully created.' }
        format.json { render :show, status: :created, location: @superpower }
      else
        format.html { render :new }
        format.json { render json: @superpower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /superpowers/1
  # PATCH/PUT /superpowers/1.json
  def update
    respond_to do |format|
      if @superpower.update(superpower_params)
        format.html { redirect_to @superpower, notice: 'Superpower was successfully updated.' }
        format.json { render :show, status: :ok, location: @superpower }
      else
        format.html { render :edit }
        format.json { render json: @superpower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /superpowers/1
  # DELETE /superpowers/1.json
  def destroy
    @superpower.destroy
    respond_to do |format|
      format.html { redirect_to superpowers_url, notice: 'Superpower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_superpower
      @superpower = Superpower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def superpower_params
      params.require(:superpower).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/superheroes_helper.rb
module SuperheroesHelper
end

app/helpers/superpowers_helper.rb
module SuperpowersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImmersiveRailsAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/superheroes/_form.html.erb
<%= form_for(superhero) do |f| %>
  <% if superhero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(superhero.errors.count, "error") %> prohibited this superhero from being saved:</h2>

      <ul>
      <% superhero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/superheroes/edit.html.erb
<h1>Editing Superhero</h1>

<%= render 'form', superhero: @superhero %>

<%= link_to 'Show', @superhero %> |
<%= link_to 'Back', superheroes_path %>

app/views/superheroes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Superheroes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @superheroes.each do |superhero| %>
      <tr>
        <td><%= superhero.name %></td>
        <td><%= link_to 'Show', superhero %></td>
        <td><%= link_to 'Edit', edit_superhero_path(superhero) %></td>
        <td><%= link_to 'Destroy', superhero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Superhero', new_superhero_path %>

app/views/superheroes/new.html.erb
<h1>New Superhero</h1>

<%= render 'form', superhero: @superhero %>

<%= link_to 'Back', superheroes_path %>

app/views/superheroes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @superhero.name %>
</p>

<%= link_to 'Edit', edit_superhero_path(@superhero) %> |
<%= link_to 'Back', superheroes_path %>

app/views/superpowers/_form.html.erb
<%= form_for(superpower) do |f| %>
  <% if superpower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(superpower.errors.count, "error") %> prohibited this superpower from being saved:</h2>

      <ul>
      <% superpower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/superpowers/edit.html.erb
<h1>Editing Superpower</h1>

<%= render 'form', superpower: @superpower %>

<%= link_to 'Show', @superpower %> |
<%= link_to 'Back', superpowers_path %>

app/views/superpowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Superpowers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @superpowers.each do |superpower| %>
      <tr>
        <td><%= superpower.name %></td>
        <td><%= link_to 'Show', superpower %></td>
        <td><%= link_to 'Edit', edit_superpower_path(superpower) %></td>
        <td><%= link_to 'Destroy', superpower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Superpower', new_superpower_path %>

app/views/superpowers/new.html.erb
<h1>New Superpower</h1>

<%= render 'form', superpower: @superpower %>

<%= link_to 'Back', superpowers_path %>

app/views/superpowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @superpower.name %>
</p>

<%= link_to 'Edit', edit_superpower_path(@superpower) %> |
<%= link_to 'Back', superpowers_path %>